spring:
  config:
    activate:
      on-profile: servers3
    import: "optional:configserver:http://3.39.179.146:9500/"
  cloud:
    config:
      name: storage
      profile: s3

encrypt:
  key: EjelT7fFw6T4LHQEuwtU